# Garimpagem de Dados

## Aula 2 - NumPy

16/05/2019

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

print('')

b = np.array([(1, 2, 3), (4, 5, 6)])
print(b)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [3]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [4]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [5]:
b - a

array([[0, 0, 0],
       [3, 3, 3]])

In [6]:
a**2

array([1, 4, 9], dtype=int32)

In [7]:
10*np.sin(a) # seno trigonométrico

array([8.41470985, 9.09297427, 1.41120008])

In [8]:
b<35

array([[ True,  True,  True],
       [ True,  True,  True]])

In [9]:
print('Axis 1: %s' % b[0])
print(np.average(b))
print(b.sum())
print(b.min())
print(b.max())

Axis 1: [1 2 3]
3.5
21
1
6


In [10]:
b.sum(axis=0) # sum of each column

array([5, 7, 9])

In [11]:
b.min(axis=1) # min of each row

array([1, 4])

In [12]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [13]:
a = np.zeros((3, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
np.ones((2,3,4), dtype=np.int16) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
np.empty([2,3]) # uninitialized, output may vary

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
c = np.full(5, 2, dtype=np.float)
print(c)

d = np.full((2, 2), 10)
print(d)

[2. 2. 2. 2. 2.]
[[10 10]
 [10 10]]


In [18]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [19]:
np.arange(0, 2, 0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [20]:
c = np.random.rand(2, 3)
print(c)

[[0.14863989 0.75841993 0.01755516]
 [0.13065307 0.09411886 0.86260908]]


In [21]:
np.transpose(c)

array([[0.14863989, 0.13065307],
       [0.75841993, 0.09411886],
       [0.01755516, 0.86260908]])

In [22]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
d[:, 0]

array([1, 4, 7])

In [25]:
d[:, 1]

array([2, 5, 8])

In [26]:
d[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [27]:
d[:, 2]

array([3, 6, 9])

In [30]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # start:stop:step

In [31]:
np.save('/tmp/x.npy', x)
del(x)
x = np.load('/tmp/x.npy')
print(x)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/x.npy'

In [32]:
# Usar memory mapping quando o conteúdo não couber em memória RAM
x_mm = np.memmap('x_mm.npy', dtype='float32', mode='w+', shape=(1000, 100))
x_mm[999][99] = 12.5
print(x_mm[999][99])

# Delete the memmap instance to close the file (the mmap file is not deleted). 
# Deletion flushes memory changes to disk before removing the object.
del(x_mm)

# Load
x_mm = np.memmap('x_mm.npy', dtype='float32', mode='r', shape=(1000, 100))
print(x_mm[999][99])

12.5
12.5


## Exercícios

1. Como calcular o tamanho da memória usada de qualquer array?
2. Crie a matriz 3x3 com valores em um range de 0 a 8
3. Crie um vetor randômico de tamanho 30 e calcule a média

In [33]:
#1
t = np.zeros((10, 10))
print('%d bytes' % (t.size * t.itemsize))

800 bytes


In [34]:
#2
f = np.arange(9).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
#3
z = np.random.random(30)

In [36]:
print(z)
print(z.mean())

[0.6855017  0.82985516 0.55985255 0.10145383 0.96749634 0.3365528
 0.20088409 0.66479762 0.89984883 0.29656516 0.02235947 0.24020832
 0.01098901 0.62780175 0.96765458 0.76951367 0.50641825 0.39114445
 0.77743982 0.85681444 0.27505768 0.86036555 0.16636934 0.31128273
 0.15625316 0.81625651 0.18600095 0.76004608 0.47102781 0.71921858]
0.514501007845884


#### 100 exercícios de NumPy

https://github.com/rougier/numpy-100