In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a.size

15

In [11]:
b = np.array([1, 2, 3])

In [12]:
b

array([1, 2, 3])

In [13]:
type(b)

numpy.ndarray

In [14]:
b.dtype

dtype('int32')

In [15]:
b = np.array([1.2, 3.5, 5.1])

In [16]:
b

array([1.2, 3.5, 5.1])

In [17]:
b.dtype

dtype('float64')

In [18]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [19]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])